version: "2"
services:
  github-star-proxy:
    build: .
    container_name: github-star-proxy
    environment:
      - VARIABLE_NAME=proxied
    env_file:
      - .env.example
      - .env
    ports:
    - "5555:80"
    restart: always
